title: Programming Adventures with Michał Kalbarczyk
author: Michał Kalbarczyk
description: Programming Adventures with Michał Kalbarczyk
url: "https://about.fazibear.me"
ga: "G-4093L52QLW"
nav_logo: about.fazibear.me
primary_color: "#d4d200"

visitors:
  path: fazibear.me
  label: "000000"
  count: "000000"

theme: "fazibear.me"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "terminal"
